### ISSUE TITLE
TypeError: Cannot destructure property 'values' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by umbreonben** [mellambias/tailwind-clip-path#2]
when I use the vscode extension tailwind-intellisense stops working and the tailwind debugger outputs this:

```
TypeError: Cannot destructure property 'values' of 'undefined' as it is undefined.
    at matchUtilities (/Users/.../node_modules/tailwindcss/lib/util/processPlugins.js:124:9)
    at setRuleWithParams (/Users/.../node_modules/tailwind-clip-path/index.js:67:5)
    at Object.handler (/Users/.../node_modules/tailwind-clip-path/index.js:106:3)
    at handler (/Users/.../.vscode/extensions/bradlc.vscode-tailwindcss-0.12.16/dist/tailwindServer.js:1762:17457)
    at /Users/.../node_modules/tailwindcss/lib/util/processPlugins.js:97:5
    at Array.forEach (<anonymous>)
    at _default (/Users/.../node_modules/tailwindcss/lib/util/processPlugins.js:91:11)
    at /Users/umbreonben/.../node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
    at LazyResult.runOnRoot (/Users/umbreonben/.../node_modules/postcss/lib/lazy-result.js:329:16)
    at LazyResult.runAsync (/Users/umbreonben/.../node_modules/postcss/lib/lazy-result.js:258:26)
```

as soon as I remove the clip-path extension tailwind-intellisense works again

**Comment by wavim** [comment]
What Tailwind version are you using? I think recent versions caused some legacy code, especially plugins, to break.

If you are using tailwindcss^4.0.0, I wrote a package [tailwindcss-clip-path](https://github.com/CarbonicSoda/tailwindcss-clip-path) that does basically the same thing, but supporting latest syntax in index.css.
